### PR TITLE
Face book login

### PR DESCRIPTION
**Pull request by clusterwin**
Initial fb login working
Don't access taylor gif insecurely. Add in check in delegate for logged in status
Add in login intercept in app delegate
Add git ignore. Remove pods from repo
Add in logout functionality in settings view controller
@gprasant @greysongregory

### CODE REVIEW

**Comment by clusterwin** [comment]
demo

**Comment by clusterwin** [comment]
demo

**Comment by gprasant** [comment]
@clusterwin  - forgot to ask you - does it remember the logged in state ? I just tried it and it doesnt seem to .

**Comment by clusterwin** [comment]
Worked for me. Let me implement the save down code we used in the twitter app.

**Pull request merged**
