### PR TITLE
adds movie comparison view in chat window for matches

### PR DESCRIPTION
**Pull request by greysongregory**
also fixes a couple bugs, with some UI changes including reversing the coloring on the chat view (to match how native ios does it)

### CODE REVIEW

**Comment by greysongregory** [comment]
also, the random movies for your match that get displayed change each time you open the chat window... couldn't think of a quick/easy fix :/

basically i seed some random numbers when creating the view, somehow I'd need to use the same set of random numbers for each specific match. will think more on it and implement something tomorrow if we think it's necessary

**Comment by clusterwin** [comment]
Could you generate the random numbers at match time? Then store them on the match.

**Comment by greysongregory** [comment]
yep, done

**Comment by clusterwin** [comment]
LGTM

**Pull request merged**
