### PR TITLE
ProfileView and Chats push transition

### PR DESCRIPTION
**Pull request by gprasant**
Hiding the heart and x buttons on the Profile View 

screen shot 2015-12-09 at 8 33 02 am

Disregard the gif in this PR. It should have been pushed up in an earlier PR

### CODE REVIEW

**Comment by clusterwin** [comment]
Looks a little bare. Should we add a bio in the data or something?

**Comment by clusterwin** [comment]
Was it not possible to hook the buttons up to their like/nope functionality?

**Comment by gprasant** [comment]
Yeah . Its harder to do it from the ProfileViewController. Would require plumbing to get the CardsViewController as a property. Just not doable in the current time

**Comment by gprasant** [comment]
Is this ok to be merged in ?

**Comment by gprasant** [comment]
Closing because PR#34 has these fixes . Dont merge in this one

**Pull request closed without merging**
