### PR TITLE
Displays chat bubbles for conversations

### PR DESCRIPTION
**Pull request by gprasant**
(Follow up from #16 )
## v3

chat_ios_default_style

Hey guys , I completed the core - Working on some auxiliaries now. You can take a look whenever you get time.  
#### ToDo
- [x] Conversation Bubbles
- [x] channel Name for 1:1 User chat (`user1:user2` ?)
- [x] Reload only the row that needs to be reloaded 
- [x] Animation
- [x] Who sent this message ? (Author) / Align left / right  depending on author
- [x] Optimistically adding sent messages to the tableView (remember to not add to the table view when you get back your published message)
- [ ] Chat history (Check if pubnub has a history feature / store last N messages for each chat room in Parse)
- [x] Dont send empty messages

### CODE REVIEW

**Comment by clusterwin** [comment]
I just opened up master and it seems the chats are not displaying properly, does this commit fix this?
@gprasant 
demo

**Comment by gprasant** [comment]
Thats probably because it doesnt show history yet. I have to merge that in yet

**Comment by clusterwin** [comment]
ok, the back button and send button are all stacked on top of each other, just wanted to make sure you're  aware

**Comment by gprasant** [comment]
thats weird. Shouldnt be the case. Ill check it out after i get some zzzs

**Pull request merged**
